name: Obtener Token de Surge

on:
  push:
    branches: [ "main" ]

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
    - name: Correr comando de registro
      run: |
        npm install -g surge
        # Esto genera un token nuevo para el correo que inventes aquí abajo
        surge token --email tucorreoinventado123@gmail.com --password MiClaveSegura123
