name: Obtener Token de Surge

on:
  push:
    branches: [ "main" ]

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
    - name: Correr comando de registro
      env:
        SURGE_LOGIN: cuenta-itla-test1234@gmail.com
        SURGE_TOKEN: token-falso-solo-para-login
      run: |
        npm install -g surge
