name: Obtener Token de Surge

on:
  push:
    branches: [ "main" ]

jobs:
  token:
    runs-on: ubuntu-latest
    steps:
    - name: Correr comando de registro
      run: |
        npm install -g surge
